# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java Build Test With Gradle

on:
  pull_request:
    branches: [ develop ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      back-end: ${{ steps.filter.outputs.back-end }}
    steps:
      - name: check if back-end directory has changed
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            back-end:
              - 'back-end/**'
  build:
    needs: changes
    if: ${{ needs.changes.outputs.back-end == 'true' }}
    runs-on: ubuntu-latest
    env:
      working-directory: ./back-end
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ${{ env.working-directory }}
