import { GpuServer } from "../features/gpuServer/gpuServerSlice";
import {
  GpuServerViewDetailResponse,
  GpuServerViewResponse,
  GpuServerViewResponses,
  SimpleGpuServer,
} from "../types";

export const gpuServersResponses: GpuServerViewResponses = {
  gpuServers: [
    {
      id: 1,
      serverName: "serverA",
      memorySize: 1024,
      diskSize: 4096,
      isOn: true,
      gpuBoard: {
        id: 1,
        modelName: "NVIDIA42",
        performance: 600,
        isWorking: true,
      },
      runningJobs: [
        {
          id: 2,
          name: "가짜 뉴스 검증을 위한 댓글 분류 학습",
          status: "RUNNING",
          memberId: 1,
        },
      ],
      waitingJobCount: 4,
      totalExpectedTime: 100,
    },
    {
      id: 2,
      serverName: "serverB",
      memorySize: 1024,
      diskSize: 1024,
      isOn: true,
      gpuBoard: {
        id: 2,
        modelName: "NVIDIA Titan V",
        performance: 700,
        isWorking: false,
      },
      runningJobs: [
        {
          id: 7,
          name: "CNN 모델을 활용한 마스크 인식 학습",
          status: "RUNNING",
          memberId: 1,
        },
      ],
      waitingJobCount: 5,
      totalExpectedTime: 45,
    },
    {
      id: 3,
      serverName: "serverC",
      memorySize: 1024,
      diskSize: 1024,
      isOn: true,
      gpuBoard: {
        id: 3,
        modelName: "RTX 6000",
        performance: 670,
        isWorking: true,
      },
      runningJobs: [
        {
          id: 8,
          name: "자연어 처리 : 문자-단위 RNN으로 이름 생성하기",
          status: "RUNNING",
          memberId: 1,
        },
      ],
      waitingJobCount: 3,
      totalExpectedTime: 10,
    },
  ],
};

export const gpuServerResponse: GpuServerViewResponse = {
  id: 1,
  serverName: "serverA",
  memorySize: 1024,
  diskSize: 4096,
  isOn: true,
  gpuBoard: {
    id: 1,
    modelName: "NVIDIA42",
    performance: 600,
    isWorking: true,
  },
  runningJobs: [
    {
      id: 2,
      name: "가짜 뉴스 검증을 위한 댓글 분류 학습",
      status: "RUNNING",
      memberId: 1,
    },
  ],
  waitingJobCount: 4,
  totalExpectedTime: 100,
};

export const simpleGpuServer: SimpleGpuServer = gpuServerResponse;

export const gpuServerDetailResponse: GpuServerViewDetailResponse = {
  id: 1,
  serverName: "serverA",
  memorySize: 1024,
  diskSize: 4096,
  isOn: true,
  gpuBoard: {
    id: 1,
    modelName: "NVIDIA42",
    performance: 600,
    isWorking: true,
  },
  jobs: [
    {
      id: 1,
      name: "영화 리뷰 분석을 통한 긍정도 평가",
      status: "COMPLETED",
      memberId: 1,
      memberName: "name",
      gpuServerId: 1,
      gpuServerName: "serverA",
      metaData: "danny/movie_review",
      expectedTime: "80",
      calculatedTime: {
        createdTime: "2021-08-12T23:01:41",
        startedTime: "2021-08-12T23:02:54",
        expectedStartedTime: "2021-08-13T02:01:41",
        completedTime: "2021-08-12T23:08:22",
        expectedCompletedTime: "2021-08-13T04:01:41",
      },
    },
    {
      id: 2,
      name: "가짜 뉴스 검증을 위한 댓글 분류 학습",
      status: "RUNNING",
      memberId: 1,
      memberName: "name",
      gpuServerId: 1,
      gpuServerName: "serverA",
      metaData: "myagya/fake_news",
      expectedTime: "50",
      calculatedTime: {
        createdTime: "2021-08-12T23:01:41",
        startedTime: "2021-08-12T23:02:54",
        expectedStartedTime: "2021-08-13T02:01:41",
        completedTime: "2021-08-12T23:08:22",
        expectedCompletedTime: "2021-08-13T04:01:41",
      },
    },
    {
      id: 3,
      name: "신경망을 이용한 스포츠 경기 비디오와 텍스트 요약",
      status: "COMPLETED",
      memberId: 1,
      memberName: "name",
      gpuServerId: 1,
      gpuServerName: "serverA",
      metaData: "better/sports_analysis",
      expectedTime: "60",
      calculatedTime: {
        createdTime: "2021-08-12T23:01:41",
        startedTime: "2021-08-12T23:02:54",
        expectedStartedTime: "2021-08-13T02:01:41",
        completedTime: "2021-08-12T23:08:22",
        expectedCompletedTime: "2021-08-13T04:01:41",
      },
    },
    {
      id: 4,
      name: "보스턴 주택 가격 예측과 k-겹 검증",
      status: "COMPLETED",
      memberId: 1,
      memberName: "name",
      gpuServerId: 1,
      gpuServerName: "serverA",
      metaData: "ed/housing_prices",
      expectedTime: "70",
      calculatedTime: {
        createdTime: "2021-08-12T23:01:41",
        startedTime: "2021-08-12T23:02:54",
        expectedStartedTime: "2021-08-13T02:01:41",
        completedTime: "2021-08-12T23:08:22",
        expectedCompletedTime: "2021-08-13T04:01:41",
      },
    },
    {
      id: 5,
      name: "소셜 미디어 게시물을 기반으로 한 우울증 감정 분석",
      status: "WAITING",
      memberId: 2,
      memberName: "name",
      gpuServerId: 1,
      gpuServerName: "serverA",
      metaData: "wannte/social_media",
      expectedTime: "20",
      calculatedTime: {
        createdTime: "2021-08-12T23:01:41",
        startedTime: "2021-08-12T23:02:54",
        expectedStartedTime: "2021-08-13T02:01:41",
        completedTime: "2021-08-12T23:08:22",
        expectedCompletedTime: "2021-08-13T04:01:41",
      },
    },
  ],
};

export const gpuServersRedux: GpuServer[] = [
  {
    id: 1,
    serverName: "serverA",
    isOn: true,
    memorySize: 1024,
    diskSize: 1024,
    performance: 600,
    modelName: "NVIDIA42",
    runningJob: {
      id: 16,
      name: "35",
      status: "RUNNING",
      memberId: 2,
    },
    waitingJobCount: 0,
    totalExpectedTime: 0,
  },
  {
    id: 2,
    serverName: "serverB",
    memorySize: 1024,
    diskSize: 1024,
    isOn: true,
    modelName: "NVIDIA Titan V",
    performance: 700,
    runningJob: {
      id: 7,
      name: "CNN 모델을 활용한 마스크 인식 학습",
      status: "RUNNING",
      memberId: 1,
    },
    waitingJobCount: 5,
    totalExpectedTime: 45,
  },
  {
    id: 3,
    serverName: "serverC",
    memorySize: 1024,
    diskSize: 1024,
    isOn: true,
    modelName: "RTX 6000",
    performance: 670,
    runningJob: {
      id: 8,
      name: "자연어 처리 : 문자-단위 RNN으로 이름 생성하기",
      status: "RUNNING",
      memberId: 1,
    },
    waitingJobCount: 3,
    totalExpectedTime: 10,
  },
];

export const gpuServerRedux: GpuServer = {
  id: 1,
  serverName: "serverA",
  memorySize: 1024,
  modelName: "NVIDIA42",
  diskSize: 4096,
  isOn: true,
  performance: 600,
  runningJob: {
    id: 2,
    name: "가짜 뉴스 검증을 위한 댓글 분류 학습",
    status: "RUNNING",
    memberId: 1,
  },
  waitingJobCount: 4,
  totalExpectedTime: 100,
};
